[build]
  command = "npm run build"

[functions]
    directory = "src/functions"

# Function-specific settings
[functions."manage-loans"]
  schedule = "0 0 * * *"

# Environment variables for production (set these in Netlify dashboard)
# VALR_API_KEY = "your-api-key"
# VALR_API_SECRET = "your-api-secret"
# DRY_RUN = "false"
# ENABLED_CURRENCIES = "ZAR,BTC,ETH"
# MIN_INCREMENT_AMOUNT = "{\"ZAR\": \"100\", \"BTC\": \"0.0001\", \"ETH\": \"0.001\"}"
# MAX_LOAN_RATIO = "0.8"